# Generated by Django 5.2.6 on 2025-09-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='фио')),
                ('acc_tg', models.CharField(max_length=100, verbose_name='ТГ аккаунт')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone', models.CharField(max_length=25, verbose_name='номер телефона')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField(verbose_name='номер вопроса')),
                ('que_text', models.TextField(blank=True, null=True, verbose_name='текст вопроса')),
                ('type_q', models.CharField(blank=True, choices=[('yes_or_no', 'yes_or_no'), ('one_of_some', 'one_of_some'), ('your_word', 'your_word')], max_length=100, null=True, verbose_name='тип вопроса')),
                ('wait_answer', models.BooleanField(blank=True, null=True, verbose_name='ожидание ответа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('kind_file', models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video'), ('audio', 'audio'), ('document', 'document')], max_length=100, null=True, verbose_name='тип вопроса')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=50, verbose_name='название опроса')),
                ('description', models.TextField(verbose_name='описание опроса')),
                ('active', models.BooleanField(verbose_name='активность опроса')),
                ('counting', models.IntegerField(blank=True, null=True, verbose_name='кол-во вопросов в опросе')),
                ('hello_text', models.TextField(blank=True, null=True, verbose_name='приветственный текст')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_text', models.TextField(verbose_name='текст кнопки')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eflab.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_tg_acc', models.CharField(max_length=100, verbose_name='ТГ аккаунт')),
                ('ans', models.TextField(verbose_name='ответ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='время ответа')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eflab.client', verbose_name='id клиента')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eflab.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eflab.survey', verbose_name='опрос'),
        ),
    ]
