# Generated by Django 5.2.6 on 2025-12-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eflab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='gifts/', verbose_name='Подарочный файл')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст, сопровождающий подарок')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eflab.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'подарок',
                'verbose_name_plural': 'подарки',
            },
        ),
    ]
