# Generated by Django 5.2.6 on 2025-12-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eflab', '0002_surveygift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind_file',
            field=models.CharField(blank=True, choices=[('photo', 'photo'), ('video', 'video'), ('audio', 'audio'), ('document', 'document')], max_length=100, null=True, verbose_name='тип файла'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_q',
            field=models.CharField(blank=True, choices=[('yes_or_no', 'yes_or_no'), ('one_of_some', 'one_of_some'), ('your_word', 'your_word'), ('on_of_many', 'on_of_many')], max_length=100, null=True, verbose_name='тип вопроса'),
        ),
    ]
